### ISSUE TITLE
[question] Will this work with typeorm >=0.3

### ISSUE THREAD

**Issue by micalevisk** [jorgebodega/typeorm-seeding#105]
Regarding the brand new version of `typeorm`: https://github.com/typeorm/typeorm/releases/tag/0.3.0 did you know if it would be easy to upgrade `typeorm-seeding` to support that last version? I'm not sure if something will break as that version is covered by the semver range

https://github.com/jorgebodega/typeorm-seeding/blob/3a9e3d30231356e7892b1e141fe1e7566b04730c/package.json#L73-L75

I'm asking this because I won't upgrade typeorm if I can't use `typeorm-seeding` (and few other packages that rely on `typeorm`)

Thanks.

**Comment by jorgebodega** [comment]
I want to try the new version, but as far as I know there are so many breaking changes, so this new version will probably take some time.

**Comment by micalevisk** [comment]
do you plan to change that semver range on `typeorm` peer dep?

**Comment by jorgebodega** [comment]
Yes, I will try to maintain support to 0.2 as much as I can, in other case there will be probably another major version to avoid breaking changes

**Comment by angelxmoreno** [comment]
I just tried this with `"typeorm": "^0.3.6"` and it works fine with the exception of script hanging on completion.
