### ISSUE TITLE
Could not import seeders!

### ISSUE THREAD

**Issue by cacpmw** [jorgebodega/typeorm-seeding#123]
I am getting this error although I think I wrote everything as stated in the docs:

```bash
✖ Could not import seeders!
Error importing seeders: Seeder RootSeeder does not exist
```

ormconfig.json:
```json
[
    {
        "name": "default",
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "mypassword",
        "database": "mydatabase",
        "logging": true,
        "synchronize": true,
        "defaultSeeder": "RootSeeder",
        "entities": [
            "./src/modules/**/infrastructure/typeorm/entities/*.ts"
        ],
        "migrations": [
            "./src/shared/infrastructure/typeorm/migrations/*.ts"
        ],
        "cli": {
            "migrationsDir": "./src/shared/infrastructure/typeorm/migrations"
        },
        "seeds": [
            "./src/shared/infrastructure/typeorm/seeders/*.ts"
        ],
        "factories": [
            "./src/shared/infrastructure/typeorm/factories/*.ts"
        ]
    }
]
```

UserFactory:
```typescript
import { Factory, FactorizedAttrs, InstanceAttribute } from "@jorgebodega/typeorm-seeding"
import { faker } from '@faker-js/faker'
import User from "@modules/users/infrastructure/typeorm/entities/User"
export default class UserFactory extends Factory<User> {
    protected entity = User
    protected attrs: FactorizedAttrs<User> = {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        email: new InstanceAttribute((instance) =>
            [instance.firstName.toLowerCase(), instance.lastName.toLowerCase(), '@email.com'].join(''),
        ),
        birthdate: faker.date.past(),
        uuid: faker.datatype.uuid(),
        password: faker.internet.password(),
        isActive: faker.datatype.boolean(),
        confirmedEmail: faker.datatype.boolean(),
        gender: faker.datatype.number({
            min: 1,
            max: 2
        })

    }
}

```

UserSeeder:
```typescript
import { Seeder } from "@jorgebodega/typeorm-seeding";
import { Connection } from "typeorm";
import UserFactory from "../factories/UserFactory";

export class UserSeeder extends Seeder {
    async run(_connection: Connection) {
        await new UserFactory().createMany(10)
    }
}
```

RootSeeder:
```typescript
import { Seeder } from "@jorgebodega/typeorm-seeding"
import { Connection } from "typeorm";
import {UserSeeder} from "./UserSeeder";

export class RootSeeder extends Seeder{
    async run(connection: Connection): Promise<void> {
        await this.call(connection, [UserSeeder])
    }

}
```

**Comment by jorgebodega** [comment]
Hi! First of all, could you try to change 
```json
"seeds":["./src/shared/infrastructure/typeorm/seeders/*.ts"],
```
to
```json
"seeders":["./src/shared/infrastructure/typeorm/seeders/*.ts"],
```

If that not works, please try to create some kind of reproducible example

**Comment by cacpmw** [comment]
@jorgebodega that did work but presented this now:

`Cannot use import statement outside a module`

**Comment by jorgebodega** [comment]
Well, that is just a problem with Node. What version are you using? Do you have `type: module` on package.json?

**Comment by cacpmw** [comment]
@jorgebodega I am using `node v16.14.0` I just added `type:module` and the error still persists

**Comment by jorgebodega** [comment]
Hmm, that is interesting. Are you using seeder from cli command or with test helper function? 

Let me check if there is something missing out there, and if you have some more information to help please provide it

**Comment by cacpmw** [comment]
@jorgebodega I had to compile the typescript code by adding this to my package.json:

```json
    "seed": "ts-node-dev -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed"
```
Then I resolved the node problem and returned to the 

`Seeder RootSeeder does not exist`

**Comment by cacpmw** [comment]
Ok, I solved it by removing the `default` word from the RootSeeder!

**Comment by KiwiKilian** [comment]
Thanks @cacpmw for the solution, I was experiencing the same problem. Maybe the docs need same info for using entities written in TypeScript (`.ts`) – or were changes introduced, which should make using `ts-node` obsolete?

**Comment by cacpmw** [comment]
> Thanks @cacpmw for the solution, I was experiencing the same problem. Maybe the docs need same info for using entities written in TypeScript (`.ts`) – or were changes introduced, which should make using `ts-node` obsolete?

I dropped this package. I believe it is not ready to be used

**Comment by TouchSek** [comment]
> > Thanks @cacpmw for the solution, I was experiencing the same problem. Maybe the docs need same info for using entities written in TypeScript (`.ts`) – or were changes introduced, which should make using `ts-node` obsolete?
> 
> I dropped this package. I believe it is not ready to be used

It seems true, i tried multiple way, but can't make it work too.  and no clear example to use.

**Comment by jorgebodega** [comment]
Guys, please.

Do not talk in closed issues, this is completely useless.

If you have something that you think it must be fixed, write or reopen an issue, provide a description and talk about it. Don't just send messages on closed issues where the people cannot see.

Try to be kind.

**Comment by jorgebodega** [comment]
I need someone of you to provide more usage information

**Comment by TouchSek** [comment]
I think the issue creator, wrote the clear information to debug.

**Comment by jorgebodega** [comment]
Clearly not. Also, the package suffer so many changes, and the issue could be outdated.

Try to be kind and productive, give some more information, like the version you're using.

**Comment by jorgebodega** [comment]
Sorry! I notice that default is missing while exporting seeders.

I added that to the README (missing, my fault) and also improve the error description.

Try again with the new version and default, please.

Edit: misclose

**Comment by zlavoie** [comment]
I think an example of how this could work with typescript (such as registering it in the package.json) would be really helpful.

**Comment by jorgebodega** [comment]
Which kind of documentation you mean? What do you think is missing?

**Comment by jorgebodega** [comment]
Closing as this is stale and probably fixed.
