### ISSUE TITLE
Future maintainance

### ISSUE THREAD

**Issue by acSpock** [jorgebodega/typeorm-seeding#129]
@jorgebodega I left a comment in the pinned issue at the forked repo here: https://github.com/w3tecch/typeorm-seeding/issues/201#issuecomment-1094559596 but I will re-paste here as dev shops are probably wondering what to do moving forward. And since you're now added as a maintainer in the original:

```
@jorgebodega I agree with @nicolasrouanne, any plans to merge the forked repo back into w3tecch now that you're a maintainer? I imagine you could merge it back and cut a major release and go from there. Would like to know going forward as upgrading to the latest typeorm breaks the current version of w3tecch/typeorm-seeding.
```

**Comment by jorgebodega** [comment]
Hi! Sorry for late response, was on vacation.

I do not want until I have, at least, permission as maintainer on repo to add some Actions to help, I don't have much time and cannot be losing more trying to deploy anything manually.

Also, I did this as the best way I can and think, but maybe the original creator don't want it that way.

Right now, I will try to maintain this fork and then will see

**Comment by acSpock** [comment]
> Hi! Sorry for late response, was on vacation.
> 
> I do not want until I have, at least, permission as maintainer on repo to add some Actions to help, I don't have much time and cannot be losing more trying to deploy anything manually.
> 
> Also, I did this as the best way I can and think, but maybe the original creator don't want it that way.
> 
> Right now, I will try to maintain this fork and then will see

Thanks for the response @jorgebodega - Cheers
