### ISSUE TITLE
SubFactory generating errors. cannot find JoinColumns of undefined

### ISSUE THREAD

**Issue by shellking4** [jorgebodega/typeorm-seeding#137]
I have this structure 

`export class AgentFactory extends Factory<Agent> {
    protected entity = Agent;
    protected attrs: FactorizedAttrs<Agent> = {
        user: new Subfactory(UserFactory),
    }
}

export class CompanyFactory extends Factory<Company> {
    protected entity = Company;
    protected attrs: FactorizedAttrs<Company> = {
        name: faker.word.noun(),
        description: faker.lorem.lines(3),
        city: faker.address.cityName(),
        email: faker.internet.email(),
        phone: faker.phone.phoneNumber(),
        address: faker.address.secondaryAddress(),
        rccm: faker.random.alphaNumeric(),
        ifu: faker.helpers.slugify(`ifu of company ${faker.company.companyName()}`),
        category: new Subfactory(CompanyCategoryFactory),
        account: new Subfactory(AccountFactory),
    }
}

export class AgentRoleFactory extends Factory<AgentRole> {
    protected entity = AgentRole;
    protected attrs: FactorizedAttrs<AgentRole> = {
      name: faker.helpers.arrayElement(["AGENT", "COMPTABLE", "SECRÉTAIRE", "DIRECTEUR TECHNIQUE"]),
      description: faker.lorem.lines(3),
    }
}

export class CareerFactory extends Factory<Career> {
    protected entity = Career;
    protected attrs: FactorizedAttrs<Career> = {
        agent: new Subfactory(AgentFactory),
        company: new Subfactory(CompanyFactory),
        role: new Subfactory(AgentRoleFactory)
    }
}`

then when seed will fail each time. How can I solve it

**Comment by jorgebodega** [comment]
Please, try to use the library [@jorgebodega/typeorm-factory](https://github.com/jorgebodega/typeorm-factory), I'm moving all the code related to factories over there

**Comment by shellking4** [comment]
Ok thank you. I will try it out

**Comment by jorgebodega** [comment]
If you have any problem, create the issue there if it is related to factories
