### ISSUE TITLE
The call method on Seeder in v5

### ISSUE THREAD

**Issue by Limonische** [jorgebodega/typeorm-seeding#168]
The call method seems to be missing from version 5. What should we use instead?

**Comment by jorgebodega** [comment]
Hi!

I removed the call method because it leads to lot of troubles, as it executes foreground seeders, and could lead to unexpected behaviours.

What is your use case?

**Comment by Limonische** [comment]
I just wanted to know what is the new way of controlling the execution order of seeders? Before I've built trees of seeders using the call method.
Also wanted to ask when there would be updated docs for version 5?
And also thanks for the great work, glad you keep this library alive!

**Comment by jorgebodega** [comment]
I'm working on this right now, maybe today or tomorrow I will release a new version with some changes and deprecations, and then I will work on documentation.

The idea right now is to use single Seeders instead of trees, that was a bad decision. And for the command, I would recommend to sort the seeders by priority, Unix style (00-UserSeeder.ts, 10-PetSeeder.ts) or the way you prefer.

Open to better ideas as well.

**Comment by Limonische** [comment]
So if I understand correctly, the current way is to have "seeders" field in the config with the glob pattern inside, which will run seeders in order according to their names?

**Comment by jorgebodega** [comment]
No, no seeders field are being checked on config, the path must be provided while executing the command.

Please, see this: https://github.com/jorgebodega/typeorm-seeding/blob/next/README.md#seed

I'm still working on this (released a `next` version yesterday) but this is gonna be the way.

**Comment by Limonische** [comment]
Hi again! I'm trying out v5.0.1. So far i've managed to run one seeder with the seed command, so something like this works:

```
./node_modules/.bin/ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed src/modules/database/seeders/Some.seeder.ts -d src/dataSource.ts
```

While the glob pattern doesnt:
```
./node_modules/.bin/ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed src/modules/database/seeders/*.seeder.{ts,js} -d src/dataSource.ts
```
I get the Unknown arguments: [list of Seeder names] error

Could you please kindly provide an example of running multiple seeders with this command?

**Comment by jorgebodega** [comment]
Glob pattern is supported by the moment using string on parameter, like this:

```./node_modules/.bin/ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed "src/modules/database/seeders/*.seeder.{ts,js}" -d src/dataSource.ts```

I'm working on supporting more than one parameter but it's the first time I'm using commander and is difficult. Probably on version 6.

**Comment by Limonische** [comment]
Awesome, it works, thanks a lot once again :)

**Comment by jorgebodega** [comment]
I will write here whenever multiple paths are available :)

**Comment by jorgebodega** [comment]
Hi! In the new version [v6.0.0-next.2](https://www.npmjs.com/package/@jorgebodega/typeorm-seeding/v/6.0.0-next.2) multiple seeder paths could be provided, like:

```bash
typeorm-seeding seed PetSeeder.ts UserSeeder.ts
typeorm-seeding seed "*Seeder.ts"
typeorm-seeding seed *Seeder.ts
```

When string is passed, the cli is using a package that calculate the files, so it will be probably removed before stable release

**Comment by Limonische** [comment]
Sorry, didn't quite get what is being removed?

**Comment by jorgebodega** [comment]
Nothing already removed, but there are plans for it.

The option to use seeders with glob pattern will be path/\*.seeder.ts instead of "path/*.seeder.ts"
