### ISSUE TITLE
No default seeders found error when running seeder

### ISSUE THREAD

**Issue by foliveirafilho** [jorgebodega/typeorm-seeding#175]
Hi. 

I'm currently upgrading a project from TypeORM v.0.2.45 to v.0.3.7 that had your [previous lib](https://github.com/w3tecch/typeorm-seeding) as dependency. Since there were a lot of breaking changes and deprecations in v.0.3.0 of TypeORM, we decided to also change the seeder library, but I've encountered some difficulties when I tried to use this lib.

I'm using the v5.0.1 of this lib and v1.2.0 of [your factory lib](https://github.com/jorgebodega/typeorm-factory).

I have the following factory class:
```ts
export class UserFactory extends Factory<UserEntity> {
  protected entity: Constructable<UserEntity>;

  protected dataSource: DataSource;

  protected attrs(): FactorizedAttrs<UserEntity> {
    return {
      fullName: faker.name.findName(),
      email: faker.internet.email(),
    };
  }
}
```

And the following seeder class (`generate-users.seeder.ts`): 
```ts
export class GenerateUsersSeeder extends Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const userRepo = dataSource.getRepository(UserEntity);
    const users = await new UserFactory().makeMany(10);

    await userRepo.insert(users);
  }
}
```

Since `ormconfig` will be removed in TypeORM v0.4.0, we've decided to drop it as well and use the new DataSource interface. The dataSource configuration is as follows:
```ts
export const DbDataSource = new DataSource({
  name: 'default',
  type: 'mysql',
  host: '127.0.0.1',
  port: 3307,
  username: 'root',
  password: 'root',
  database: 'db-test',
  timezone: 'Z',
  dateStrings: ['DATE'],
  synchronize: false,
  entities: ['./src/**/*.entity{.ts,.js}'],
  logging: 'all',
  logger: 'advanced-console',
  maxQueryExecutionTime: 180000,
  cache: false,
  migrations: ['./src/database/migrations/**/*{.ts,.js}'],
});
```

The problem is when I run:
```bash
yarn typeorm-seeding seed -d src/database/main-db/db-data-source.ts src/database/seeds/user/generate-users.seeder.ts
```
I get the following error:
```bash
Could not load seeders!
Error: No default seeders found
```

I would be very much aprecciated if you could help me. If you need any more information, please let me know! It's my first issue in an open source repo :)

**Comment by jorgebodega** [comment]
Hi!

If no special operations are needed while persisting your entities, you can use `createMany` instead of `makeMany`.

But your problem is that your seeder has no default in export, that is required by CLI.

**Comment by foliveirafilho** [comment]
Thanks, it solved the previous error. But now it shows the following:
```bash
TypeError: this.entity is not a constructor
```

**Comment by jorgebodega** [comment]
`entity` field in factories should be just the class, no `Constructable` type needed. But is just a type, so it should not fail.

Can you try with just `protected entity: UserEntity`?

**Comment by foliveirafilho** [comment]
It seems like the class `UserEntity` does not match the `Constructable` type:

![image](https://user-images.githubusercontent.com/36215435/186776204-b0c788e5-9897-439c-8ec8-3065e805a8b8.png)

**Comment by jorgebodega** [comment]
Can you paste the content of that file? Seems like there is no constructor

**Comment by foliveirafilho** [comment]
I've removed most of its props so its easier to see:

```ts
export class UserEntity
  extends BaseEntityWithRandomIdAndDates
  implements UpdatableEntity<Partial<UserEntity>>
{
  fullName: string;

  email: string;

  setValues(partialVals: Partial<UserEntity>): this {
    Object.assign(this, partialVals);
    return this;
  }
}
```

```ts
export class BaseEntityWithRandomIdAndDates {
  id: number;

  createdAt: Date;

  updatedAt: Date;
}
```

```ts
export interface UpdatableEntity<UpdateEntityDto = unknown> {
  setValues(partialVal: UpdateEntityDto): this;
}
```

**Comment by jorgebodega** [comment]
Hmm, I think it should work, the class should have a default constructor. Can you prepare an example repo? 

I can take a deeper look on this tomorrow.

**Comment by foliveirafilho** [comment]
Here's the example repo:

https://github.com/foliveirafilho/typeorm-seeding-cli-error

It's not fully functional because, for some reason, the CLI isn't working properly when loading the data source file and I could not find the reason why :(

**Comment by jorgebodega** [comment]
I left a comment in the repo, pls check that 😃

**Comment by foliveirafilho** [comment]
Turns out we need to provide the class in the `entity` field of the factory. In other words:

```diff
- protected entity: UserEntity;
+ protected entity = UserEntity;
```

And it works as it should! Thank you @jorgebodega for your help!

**Comment by Patrick-Erichsen** [comment]
I ran into this same issue after some LLM generated code wrote an `implements` rather than `extends`, e.g.

```diff
- export default class UserSeeder implements Seeder {
+ export default class UserSeeder extends Seeder {
```

Thanks for the great work here @jorgebodega ! Spent a good hour plus trying to get `typeorm-extension` to run, couldn't run `typeorm-seeding` because they haven't upgraded to typeorm 0.3, but this fork is working like a charm 👍
