### ISSUE TITLE
Incorrect usage of `glob.sync` in `src/utils/fileHandling.ts`

### ISSUE THREAD

**Issue by alumni** [jorgebodega/typeorm-seeding#184]
Glob patterns allow only `/` as path separators, independent of platform.

However, `process.cwd()` and `path.resolve()` will use `\` as path separators on Windows.

Instead of: 

```ts 
return glob.sync(path.resolve(process.cwd(), filePattern), { ignore: '**/node_modules/**' })
```

a correct usage would be:

```ts
return glob.sync(filePattern, { ignore: '**/node_modules/**', absolute: true });
```

Note: `glob` also has the [cwd option](https://github.com/isaacs/node-glob#options) which would default to `process.cwd()` anyway, so no need pass it.

_Later Edit:_ I understand why the `path.resolve` was called. If you need absolute path, `glob` has an option: `{ absolute: true }`.

**Comment by jorgebodega** [comment]
Oh, that is nice!

I'm gonna let the PR run the tests, and then merge. I don't work on Windows, so this kind of help is very appreciated.

**Comment by jorgebodega** [comment]
Released!
