### ISSUE TITLE
CLI Error: No default seeders found. Windows

### ISSUE THREAD

**Issue by WittmannD** [jorgebodega/typeorm-seeding#193]
Hi. I try to run the following command:
```bash
ts-node ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js -d src/database/dataSource.ts seed "src/database/seeders/user.seeder.ts"
```
It works fine when i run it from docker container bash. But when i try to run it from windows cmd it throw me the error.
```
√ Datasource loaded
× Could not load seeders!
Error: No default seeders found
...
```

Versions i'm using:
```
"@jorgebodega/typeorm-factory": "^1.2.0",
"@jorgebodega/typeorm-seeding": "^5.0.2",
```

User factory class
```ts
export class UserFactory extends Factory<UserEntity> {
  protected entity = UserEntity;
  protected dataSource = dataSource;  // data source from src/database/dataSource.ts
  protected attrs(): FactorizedAttrs<UserEntity> {
    return {
      refreshTokenHash: '',
      email: faker.internet.email,
      lastName: faker.name.lastName,
      firstName: faker.name.firstName,
      password: async () => await hash('testdata', await genSalt(3)),
      wallet: [],
    };
  }
}
```

User seeder (src/database/seeders/user.seeder.ts)
```ts
export default class UserSeeder extends Seeder {
  async run() {
    await new UserFactory().create();
  }
}
```

Typeorm data source (src/database/dataSource.ts)
```ts
export default new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT, 10),
  username: process.env.POSTGRES_USER,
  password: process.env.POSTGRES_PASSWORD,
  database: process.env.POSTGRES_DB,
  autoLoadEntities: true,
  synchronize: false,
  entities: [join(__dirname, '../', '**/*.entity{.ts,.js}')],
  migrations: [join(__dirname, '../', 'database/migrations/**/*{.ts,.js}')],
});
```

I'm not sure, but maybe the problem is that method `resolve` return path with double backslashes which is then passed to the `Glob.sync` method.
https://github.com/jorgebodega/typeorm-seeding/blob/5b704ea5624b9ca046980e689501e448ad60f142/src/commands/seed.command.ts#L62

[The glob package docs say](https://github.com/isaacs/node-glob#windows) that you should only use forward slashes to define a path.

I would really appreciate your help.

**Comment by jorgebodega** [comment]
Hi! I don't work on Windows, so I cannot reproduce this. It would help if you can reproduce this in a repo, to have a check. Thanks!

**Comment by gabrielsmenezes** [comment]
Same problem here

**Comment by jorgebodega** [comment]
Hi! Could someone check if this is already working on `v6`? This could be failing due to #185

**Comment by ahmadxgani** [comment]
Got same error here, I try to run the following command: `ts-node ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js -d datasource.ts seed "./database/seeder/*.seed.ts"`

and got error as shown below:
![image](https://user-images.githubusercontent.com/73988956/208239845-515c124e-1e70-48d8-ae61-251927466103.png)

`seeder (database/seeder/tag.seed.ts):`
```ts
import { Seeder } from '@jorgebodega/typeorm-seeding';
import type { DataSource } from 'typeorm';
import { Tag } from '../../src/modules/tag/tag.entity';

export class CreateTag extends Seeder {
  public async run(dataSource: DataSource): Promise<void> {
    const tagRepo = dataSource.getRepository(Tag);
    tagRepo.create(
      [
        'javascript',
        'html',
        'css',
        'php',
        'golang',
        'nodejs',
        'rust',
        'kotlin',
        'java',
        'python',
      ].map((tag) => ({ name: tag })),
    );
  }
}
```

`typeorm datasource:`
```ts
import { DataSource } from 'typeorm';
const path = require('path');
const envConfig = require('dotenv').config({
  path: path.resolve(__dirname, '.env'),
});

function env(key: string) {
  return envConfig.parsed[key] || process.env[key];
}

export default new DataSource({
  type: env('DB_DIALECT'),
  host: env('DB_HOST'),
  port: env('DB_PORT'),
  username: env('DB_USERNAME'),
  password: env('DB_PASSWORD'),
  database: env('DB_NAME'),
  entities: [__dirname + '/**/*.entity.ts'],
  logger: 'advanced-console',
  logging: ['warn', 'error'],
  synchronize: false,
});
```

`Versions i'm using:`
```json
"@jorgebodega/typeorm-seeding": "^6.0.0"
```

I would really appreciate your help.

**Comment by jorgebodega** [comment]
Hi! I'm going to take a look this weekend, sorry for late response!

**Comment by jorgebodega** [comment]
Sorry! I notice that `default` is missing while exporting seeders.

I added that to the README (missing, my fault) and also improve the error description.

Try again with the new version and default, please.

**Comment by SeishinKeiji** [comment]
> Sorry! I notice that `default` is missing while exporting seeders.
> 
> I added that to the README (missing, my fault) and also improve the error description.
> 
> Try again with the new version and default, please.

Thanks for your help! solved :+1:

**Comment by ahmadxgani** [comment]
> Sorry! I notice that `default` is missing while exporting seeders.
> 
> I added that to the README (missing, my fault) and also improve the error description.
> 
> Try again with the new version and default, please.

Thanks for your help! now my problem solved :+1:
