### ISSUE TITLE
Explanation migration from w3tecch/typeorm-seeding to this library

### ISSUE THREAD

**Issue by abdul15irsyad** [jorgebodega/typeorm-seeding#216]
hi i used typeorm-seeding library since the previous version [https://github.com/w3tecch/typeorm-seeding](https://github.com/w3tecch/typeorm-seeding), then i found your library and it helped me a lot, but i found a problem when migrating from w3tecch/typeorm-seeding, i think it is better to give instructions regarding migration from previous one because there are some differences in the syntax for example the use of extends instead of implements

in the previous version
```ts
export default class UserSeeder implements Seeder { . . . }
```
**when this seeder command is executed the seeder file does not run seeding process and does not display warning information**

i miss the changes in documentation to use `extends` instead of `implements`
```ts
export default class UserSeeder extends Seeder { . . . }
```

**Comment by jorgebodega** [comment]
The readme now explains how it works, only one thing is missing but I will not write a migration guide when the readme is available
