### ISSUE TITLE
Bug with noImplicitAny and noUnusedParameters

### ISSUE THREAD

**Issue by Eirmas** [jorgebodega/typeorm-seeding#217]
# Bug with `noImplicitAny` and `noUnusedParameters`

With `noImplicitAny=true` or `noUnusedParameters=true` in tsconfig.json, the CLI fails.

Fix: remove unused parameters and any types

Version affected: 6.0.0

Console output:

```
> ts-node ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js -d src/config/postgres.config.ts seeders/*.ts

✔ Datasource loaded
✖ Could not load seeders!
SeederImportationError: Could not load seeders!
    at Command.run (/<hidden>/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:40:11)
    at async Command.parseAsync (/<hidden>/node_modules/@jorgebodega/typeorm-seeding/node_modules/commander/lib/command.js:916:5)
    at async bootstrap (/<hidden>/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:73:3)
```

**Comment by jorgebodega** [comment]
Let me try this weekend, sorry for late response!

**Comment by jorgebodega** [comment]
Sorry! I notice that default is missing while exporting seeders.

I added that to the README (missing, my fault) and also improve the error description.

Try again with the new version and default, please.

**Comment by Eirmas** [comment]
Thanks, I will try!

Unrelated to the issue, but are you planning on improving the error messages for the seeders? It would be really nice to get the actuall error message when a seeder fail instead of a "Seeders could not execute".

**Comment by jorgebodega** [comment]
Yes, I will try to improve the code loading file per file, instead of everyone together.

That could help to identify which file is not executing their seeder.

**Comment by Eirmas** [comment]
Would it also show the error given in the seeder? I personaly have 1 seeder file, and when it fails it would fail with a typeorm error "user already exists" or something along those lines. For that usage it would be nice to receive that error directly in the console, as I now have to spin it up manually outside a seeder to find out whats wrong.
Great library none the less 👍
