### ISSUE TITLE
Hey, How can I execute your Seeding???

### ISSUE THREAD

**Issue by godtaehee** [jorgebodega/typeorm-seeding#230]
In Typeorm-Seeding, there are some command lines which is provided by default.

https://www.npmjs.com/package/typeorm-seeding#cli-configuration

So I can seed to my database, but I think there are any no execution method in your library.

Can you help me?

**Comment by jorgebodega** [comment]
Hi! Are you sure this is a problem related with this library? If your problem is with seeding, I will move this issue to the other repo.

**Comment by godtaehee** [comment]
Nope, I wanna seed my local database with your library.

In Typeorm-Seeding, I can make command like `seed:run`.

So when I execute the command `npm run seed:run`, I can seed to my local db.

Like above, I wanna know how to execute your library for seeding local database.

**Comment by jorgebodega** [comment]
Please, check the readme to see the new differences.

Open a new issue if you have any other problem.
