### ISSUE TITLE
Driver not Connected

### ISSUE THREAD

**Issue by ahmadxgani** [jorgebodega/typeorm-seeding#237]
i try to run `ts-node -r tsconfig-paths/register ./node_modules/@jorgebodega/typeorm-seeding/dist/cli.js seed -d src/database/datasource.ts src/database/seeder.ts` ( the typeorm-seeding command throw an error ✖ Could not load the data source!, so i use ts-node instead, idk why :thinking: )
and got this error:
![image](https://user-images.githubusercontent.com/73988956/212690706-9b966dac-6aac-45fe-a719-b3f841a4fdc7.png)

i don't know why my fastify app success initialize the connection while the typeorm-seeding package throw the error above, this issue also mentioned on [typeorm issue](https://github.com/typeorm/typeorm/issues/8079)

datasource.ts
```typescript

import "dotenv/config";
import path from "path";
import { DataSource } from "typeorm";

export const datasource = new DataSource({
  type: "postgres",
  host: process.env.DB_HOST,
  port: process.env.DB_PORT as unknown as number,
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  synchronize: true,
  entities: [path.resolve(__dirname, "../plugins/**/*.entity.{js,ts}")],
});
```

seeder.ts
```typescript
import { Seeder } from "@jorgebodega/typeorm-seeding";
import { UserEntity } from "plugins/user/user.entity";
import { DataSource } from "typeorm";
export default class UserSeeder extends Seeder {
  public async run(dataSource: DataSource) {
    const userRepository = dataSource.getRepository(UserEntity);
    const user = userRepository.create({ username: "shinigami", email: "test@c.c", password: "verysecr3t" });
    userRepository.save(user);
  }
}
```

package version
```json
"@jorgebodega/typeorm-seeding": "^6.0.1"
"typeorm": "^0.3.11"
"pg": "^8.8.0"
```

I would really appreciate your help.

**Comment by jorgebodega** [comment]
Well, as far as I understand in the issue, and also the issue related from typeorm, is something related to the driver, and this library has nothing related to the library, it uses the API exposed by TypeORM.

I think this issue should be in TypeORM repository. Unless you have some more information...

**Comment by ahmadxgani** [comment]
I appreciate your swift reply, closed.

**Comment by ChrisPlease** [comment]
@SeishinKeiji btw, I got stuck on this, was because I wasn't `await`ing the db interactions.

**Comment by ahmadxgani** [comment]
> @SeishinKeiji btw, I got stuck on this, was because I wasn't `await`ing the db interactions. 

Ahh my fault, big thanks for your comment @ChrisPlease 😁
