### ISSUE TITLE
Taking DataSource connection values from configService/Joi

### ISSUE THREAD

**Issue by willzarem** [jorgebodega/typeorm-seeding#291]
I have my project set up to load the env variables from a joi validation schema into nest.js ConfigService, however, since the DataSource gets called from outside Nest.js' lifecycle there's no way of doing dependency injection.  

Any idea how I could get those values without duplicating credentials?

```
TypeOrmModule.forRootAsync({
    imports: [ConfigModule],
    inject: [ConfigService],
    useFactory: async (configService: ConfigService) => ({
      type: 'postgres',
      host: configService.get('DB_HOST'),
      port: configService.get('DB_PORT'),
      username: configService.get('DB_USERNAME'),
      password: configService.get('DB_PASSWORD'),
      database: configService.get('DB_DATABASE'),
      autoLoadEntities: true,
      synchronize: true,
    }),
  }),
```

**Comment by jorgebodega** [comment]
This library is only coupled to TypeORM, just like NestJS with that module. So, the only way to run the script is to isolate the datasource outside the NestJS module, or [preparing a script to run](https://docs.nestjs.com/recipes/nest-commander) inside the system.

Feel free to reopen this if needed!
