### ISSUE TITLE
Faker library incident

### ISSUE THREAD

**Issue by bartosjiri** [jorgebodega/typeorm-seeding#46]
*(Referencing the original issue: https://github.com/w3tecch/typeorm-seeding/issues/204)*

> Looks like the [Faker.js](https://github.com/marak/Faker.js/) library has been either compromised or discontinued in a strange manner.
> 
> I believe it would be the best to replace this library, since it is provided as a parameter into entity factories. What are some suitable alternatives?

**Comment by jorgebodega** [comment]
Same response as https://github.com/w3tecch/typeorm-seeding/issues/204#issuecomment-1005775052

Starting on version 3, which is available now on `next` tag, faker is removed as a dependency. Is not required and takes too much size on final bundle.
