### ISSUE TITLE
Swap out Faker for @faker-js/faker

### ISSUE THREAD

**Issue by kevin-mitchell** [jorgebodega/typeorm-seeding#71]
_note: sorry in advance, this is a copy / paste from the original project. I'm new to the library and am not sure what the history is or future for the project, i.e. if this repo will become the more popular fork, etc, but either way I wanted to raise the issue here as well!_

After the "switcheroo" [that was pulled with Faker](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/), I imagine that it would be a good idea to switch Faker out for the accepted "official" fork of the original project.

See: https://fakerjs.dev/

My understanding is that the best way to approach this swap would be to wait for the 6.0.0 release of `@faker-js/faker` (as of this ticket being created the current package is `6.0.0-alpha.5`), then "just" swap out the libraries.

In a very quick test I found that it seems pretty simple to swap out "old faker" for "new faker", although I followed these steps https://github.com/faker-js/faker#typescript-support to make TypeScript happy (this may be unnecessary).

**Comment by kevin-mitchell** [comment]
FYI @jorgebodega I saw your comment https://github.com/w3tecch/typeorm-seeding/issues/201 and so made this issue here as well :) - let me know if you'd prefer I do this in a different way!

**Comment by jorgebodega** [comment]
Hi! It is okay, don't worry.

This is not an "official' fork, but I was a collaborator on the original one. The changes you can see here on v2 are just some fixes and refactor. After v3, there are some changes just on my own responsability.

As you can see, on v2 faker is on dependencies https://github.com/jorgebodega/typeorm-seeding/blob/3b53a05b4490fec407721e5212e379ef1bf1021d/package.json#L64

On v3 and after that, faker has been removed from dependencies, so final users don't need to worry about that, they can install the package they want.

Use whatever version you want ;)
