### ISSUE TITLE
Improve documentation for default seeder

### ISSUE THREAD

**Issue by lparolari** [jorgebodega/typeorm-seeding#75]
Hi! Thank you for the awesome work you do maintaining this library.

Please consider to mention in documentation that seeder classes should be exported without default export if the `defaultSeeder` configuration is set to the name of the seeder as you show in examples ("RootSeeder").

I just wasted one hour figuring out why my default seeder was not found. Maybe the solution was trivial, but not for me :)
Hope this may help other peoples.

Thank you.

**Comment by jorgebodega** [comment]
Yes, documentation is something that i have to improve on this library. Unfortunately, I don't have enough time to do, at least by the moment. 

Sorry if you spent too many time trying to make that work, will be great to know what was the problem and add it to docs

**Comment by lparolari** [comment]
No problem, it's my misunderstanding! 

In the next days I'll try to open a PR, I'm glad to help :)

**Comment by lparolari** [comment]
Just for information:

## Problem

1. create a seeder

```js
// ./path/to/seeder/RootSeeder.ts

export default class RootSeeder extends Seeder {  // <-- note the keyword "default"
  async run(connection: Connection): Promise<void> {
    // ...
  }
}
```

2. set the default seeder in config (in my case, `ormconfig.json`

```json
{
  ...
  "seeders": ["./path/to/seeders/*.ts"],
  "defaultSeeder": "RootSeeder"
  ...
}
```

## Error

```
✔ ORM Config loaded
✖ Could not import seeders!
Error importing seeders: Seeder RootSeeder does not exist
error Command failed with exit code 1.
```

## Expected behavior

It finds the seeder `RootSeeder` and executes seeding.

## Solutions

### Solution 1

*(Recommended, in my opinion)*

Remove the `default` export from `RootSeeder`:

```js
// ./path/to/seeder/RootSeeder.ts

export class RootSeeder extends Seeder {  // <-- "default" removed
  async run(connection: Connection): Promise<void> {
    // ...
  }
}
```

### Solution 2

Update the `ormconfig.json` to

```json
{
  ...
  "seeders": ["./path/to/seeders/*.ts"],
  "defaultSeeder": "default"
  ...
}
```

Please note that in this case, if you export more than one default seeder only the latest loaded will be executed.

**Comment by jorgebodega** [comment]
Mmm I will check this on this week or weekend, don't have too much time.

Thanks for your work!

**Comment by jorgebodega** [comment]
Sorry about the delay, just merge the PR

I will work on this next week, need to improve that functionality
